<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => '',
    'Акция' => '',
    'Артикул' => '',
    'В наличии' => '',
    'В настоящий момент к категории данного товара не привязан ни один фильтр. Управлять фильтрами можно' => '',
    'Выберите бренд ...' => '',
    'Выберите категорию ...' => '',
    'Главная категория' => '',
    'Да' => '',
    'Деревом' => '',
    'Добавить' => '',
    'Добавить товар' => '',
    'Доп. категории ...' => '',
    'Доп. поля' => '',
    'Идентификатор' => '',
    'Картинки' => '',
    'Карточка товара' => '',
    'Категории' => '',
    'Количество на складах' => '',
    'Короткий текст' => '',
    'Магазин' => '',
    'Модификации' => '',
    'Название' => '',
    'Не обязательно' => '',
    'Нет' => '',
    'Новинка' => '',
    'Обновить' => '',
    'Остаток' => '',
    'Поля не заданы. Задать можно' => '',
    'Популярное' => '',
    'Поступление' => '',
    'Производитель' => '',
    'СЕО-имя' => '',
    'Связанные продукты' => '',
    'Создать категорию' => '',
    'Сортировка' => '',
    'Текст' => '',
    'Типы цен' => '',
    'Товар' => '',
    'Товары' => '',
    'У товара нет цен.' => '',
    'Фильтры' => '',
    'Цены' => '',
    'Штрихкод' => '',
    'здесь' => '',
];
